export const assetsItems = [
  {
    name: "Ball",
    image: require("../assets/iconblocks/ball.png"),
    sound: "../assets/audio/ball.mp3",
    category: "To Play",
    is_category: "0",
  },
  {
    name: "Banana",
    image: require("../assets/iconblocks/banana.png"),
    sound: "../assets/audio/banana.mp3",
    category: "To Eat",
    is_category: "0",
  },
  {
    name: "Basketball",
    image: require("../assets/iconblocks/basketball.png"),
    sound: require("../assets/audio/basketball.mp3"),
    category: "To Play",
    is_category: "0",
  },
  {
    name: "Bike",
    image: require("../assets/iconblocks/bike.png"),
    sound: require("../assets/audio/bike.mp3"),
    category: "Home",
    is_category: "0",
  },
  {
    name: "Book",
    image: require("../assets/iconblocks/book.png"),
    sound: require("../assets/audio/book.mp3"),
    category: "To Play",
    is_category: "0",
  },
  {
    name: "Bread",
    image: require("../assets/iconblocks/bread.png"),
    sound: require("../assets/audio/bread.mp3"),
    category: "To Eat",
    is_category: "0",
  },
  {
    name: "Broccoli",
    image: require("../assets/iconblocks/broccoli.png"),
    sound: require("../assets/audio/broccoli.mp3"),
    category: "To Eat",
    is_category: "0",
  },
  {
    name: "Carrot",
    image: require("../assets/iconblocks/carrot.png"),
    sound: require("../assets/audio/carrot.mp3"),
    category: "To Eat",
    is_category: "0",
  },
  {
    name: "Cheese",
    image: require("../assets/iconblocks/cheese.png"),
    sound: require("../assets/audio/cheese.mp3"),
    category: "To Eat",
    is_category: "0",
  },
  //   {
  //     name: "Cherry",
  //     image: require("../assets/iconblocks/chery.png"),
  //     sound: require("../assets/audio/chery.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  //   {
  //     name: "Chicken",
  //     image: require("../assets/iconblocks/chicken.png"),
  //     sound: require("../assets/audio/chicken.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  {
    name: "Coloring",
    image: require("../assets/iconblocks/coloring.png"),
    sound: require("../assets/audio/coloring.mp3"),
    category: "To Play",
    is_category: "0",
  },
  {
    name: "Computer",
    image: require("../assets/iconblocks/computer.png"),
    sound: require("../assets/audio/computer.mp3"),
    category: "To Play",
    is_category: "0",
  },
  {
    name: "Cookie",
    image: require("../assets/iconblocks/cookie.png"),
    sound: require("../assets/audio/cookie.mp3"),
    category: "To Eat",
    is_category: "0",
  },
  {
    name: "Croissant",
    image: require("../assets/iconblocks/croissant.png"),
    sound: require("../assets/audio/croissant.mp3"),
    category: "To Eat",
    is_category: "0",
  },
  {
    name: "Cucumber",
    image: require("../assets/iconblocks/cucumber.png"),
    sound: require("../assets/audio/cucumber.mp3"),
    category: "To Eat",
    is_category: "0",
  },
  {
    name: "Dog",
    image: require("../assets/iconblocks/dog.png"),
    sound: require("../assets/audio/dog.mp3"),
    category: "More",
    is_category: "0",
  },
  {
    name: "Doll",
    image: require("../assets/iconblocks/doll.png"),
    sound: require("../assets/audio/doll.mp3"),
    category: "To Play",
    is_category: "0",
  },
  {
    name: "Drink",
    image: require("../assets/iconblocks/drink.png"),
    sound: require("../assets/audio/drink.mp3"),
    category: "Home",
    is_category: "0",
  },
  {
    name: "Earset",
    image: require("../assets/iconblocks/earset.png"),
    sound: require("../assets/audio/earset.mp3"),
    category: "Tools",
    is_category: "0",
  },
  {
    name: "Ear",
    image: require("../assets/iconblocks/ear.png"),
    sound: require("../assets/audio/earset.mp3"),
    category: "More",
    is_category: "0",
  },
  {
    name: "Egg",
    image: require("../assets/iconblocks/egg.png"),
    sound: require("../assets/audio/egg.mp3"),
    category: "To Eat",
    is_category: "0",
  },
  {
    name: "Exercise",
    image: require("../assets/iconblocks/exercise.png"),
    sound: require("../assets/audio/exercise.mp3"),
    category: "Verbs",
    is_category: "0",
  },
  {
    name: "Eyes",
    image: require("../assets/iconblocks/eyes.png"),
    sound: require("../assets/audio/eyes.mp3"),
    category: "More",
    is_category: "0",
  },
  {
    name: "Feel",
    image: require("../assets/iconblocks/feel.png"),
    sound: require("../assets/audio/feel.mp3"),
    category: "Home",
    is_category: "1",
  },
  {
    name: "Food",
    image: require("../assets/iconblocks/food.png"),
    sound: require("../assets/audio/food.mp3"),
    category: "More",
    is_category: "0",
  },
  {
    name: "Tools",
    image: require("../assets/iconblocks/tools.png"),
    sound: null,
    category: "Home",
    is_category: "1",
  },
  {
    name: "To Eat",
    image: require("../assets/iconblocks/to_eat.png"),
    sound: require("../assets/audio/to_play.mp3"),
    category: "Home",
    is_category: "1",
  },
  {
    name: "To Play",
    image: require("../assets/iconblocks/to_play.png"),
    sound: require("../assets/audio/to_play.mp3"),
    category: "Home",
    is_category: "1",
  },
  {
    name: "More",
    image: require("../assets/iconblocks/more.png"),
    sound: null,
    category: "Home",
    is_category: "1",
  },
  {
    name: "Want",
    image: require("../assets/iconblocks/want.png"),
    sound: require("../assets/audio/want.mp3"),
    category: "Home",
    is_category: "0",
  },
  {
    name: "I",
    image: require("../assets/i.png"),
    sound: require("../assets/audio/i.mp3"),
    category: "Home",
    is_category: "0",
  },
  //   {
  //     name: "apple",
  //     image: require("../assets/iconblocks/apple.png"),
  //     sound: require("../assets/audio/apple.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  //   {
  //     name: "apple",
  //     image: require("../assets/iconblocks/apple.png"),
  //     sound: require("../assets/audio/apple.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  //   {
  //     name: "apple",
  //     image: require("../assets/iconblocks/apple.png"),
  //     sound: require("../assets/audio/apple.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  //   {
  //     name: "apple",
  //     image: require("../assets/iconblocks/apple.png"),
  //     sound: require("../assets/audio/apple.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  //   {
  //     name: "apple",
  //     image: require("../assets/iconblocks/apple.png"),
  //     sound: require("../assets/audio/apple.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  //   {
  //     name: "apple",
  //     image: require("../assets/iconblocks/apple.png"),
  //     sound: require("../assets/audio/apple.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  //   {
  //     name: "apple",
  //     image: require("../assets/iconblocks/apple.png"),
  //     sound: require("../assets/audio/apple.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  //   {
  //     name: "apple",
  //     image: require("../assets/iconblocks/apple.png"),
  //     sound: require("../assets/audio/apple.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  //   {
  //     name: "apple",
  //     image: require("../assets/iconblocks/apple.png"),
  //     sound: require("../assets/audio/apple.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  //   {
  //     name: "apple",
  //     image: require("../assets/iconblocks/apple.png"),
  //     sound: require("../assets/audio/apple.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  //   {
  //     name: "apple",
  //     image: require("../assets/iconblocks/apple.png"),
  //     sound: require("../assets/audio/apple.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  //   {
  //     name: "apple",
  //     image: require("../assets/iconblocks/apple.png"),
  //     sound: require("../assets/audio/apple.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  //   {
  //     name: "apple",
  //     image: require("../assets/iconblocks/apple.png"),
  //     sound: require("../assets/audio/apple.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  //   {
  //     name: "apple",
  //     image: require("../assets/iconblocks/apple.png"),
  //     sound: require("../assets/audio/apple.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
  //   {
  //     name: "apple",
  //     image: require("../assets/iconblocks/apple.png"),
  //     sound: require("../assets/audio/apple.mp3"),
  //     category: "To Eat",
  //     is_category: "0",
  //   },
];
