export const en = {
  button_your_character: "Make your own",
  header_choose_character: "Choose a Character",
  settings_text_about: "About",
  settings_text_donate: "Donate",
  settings_text_general: "General",
  settings_text_language: "Language",
  settings_text_layout: "View and Layout Settings",
  settings_text_support: "Support",
  settings_text_symbolName: "Name below Symbol",
  text_audio: "Audio",
  text_category: "Category",
  text_delete: "Delete",
  text_edit: "Edit",
  text_enter: "Enter this number: ",
  text_name: "Name",
  text_play: "Play",
  text_record: "Record",
};

export const mk = {
  button_your_character: "Изберете ваш",
  header_choose_character: "Изберете карактер",
  settings_text_about: "За нас",
  settings_text_donate: "Донации",
  settings_text_general: "Општо",
  settings_text_language: "Јазик",
  settings_text_layout: "Изглед",
  settings_text_support: "Поддршка",
  settings_text_symbolName: "Име под Симболот",
  text_audio: "Звук",
  text_category: "Категорија",
  text_delete: "Избриши",
  text_edit: "Измени",
  text_enter: "Внесете го овој број: ",
  text_name: "Име",
  text_play: "Слушни",
  text_record: "Сними",
};
